Manis work
DCC-EX/EX-WebThrottle2 pull request #10
Opened 2022-11-12 10:44 UTC by ManiAkasapu

Font file added.

2022-11-12 11:45 UTC, matt-hu commented
@ManiAkasapu In future make sure your pull requests target `next-release`, not `main`

2022-11-13 08:05 UTC, ManiAkasapu commented
Oh! You have already changed the base branch.. Thanks. I may have overlooked it.

2022-11-13 14:02 UTC, matt-hu commented
@ManiAkasapu I like the look of what you've done, but currently it will remove lots of the work @dexslab has done to add custom themes. I'm not entirely sure the best way to rectify this.

2022-11-13 14:05 UTC, matt-hu requested changes
I've added a comment to show where the theme selector has been removed

2022-11-13 14:05 UTC, matt-hu commented on src/App.vue
> -    <v-footer height="25">
This section here has been removed, but this is the theme selector switch

2022-11-13 14:27 UTC, matt-hu commented on src/App.vue
> -    <v-footer height="25">
I've just noticed that #8 does remove some of that so I'll have another look once that's merged

2022-11-14 00:24 UTC, ManiAkasapu commented
I think something wrong happened..  I have not edited those..  When I compare, it is same as next-release.. I have to look into it.. 
Thanks looking.. Can you close or reject this PR..

2022-11-23 14:47 UTC, dexslab commented
Please merge the changes from next-release i finally closed my PR

2022-11-26 12:13 UTC, closed without merging